CREATE TABLE IF NOT EXISTS profile (
  id SMALLINT PRIMARY KEY CHECK (id = 1), full_name TEXT NOT NULL, role TEXT NOT NULL, summary TEXT NOT NULL,
  availability TEXT NOT NULL, location TEXT NOT NULL, brand TEXT NOT NULL, eyebrow TEXT NOT NULL,
  about_title TEXT NOT NULL, experience_title TEXT NOT NULL, projects_title TEXT NOT NULL, skills_title TEXT NOT NULL,
  education_title TEXT NOT NULL, contact_title TEXT NOT NULL, contact_cta TEXT NOT NULL, status_label TEXT NOT NULL, online_text TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS navigation (position SMALLINT PRIMARY KEY, label TEXT NOT NULL, href TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS social_link (position SMALLINT PRIMARY KEY, label TEXT NOT NULL UNIQUE, value TEXT NOT NULL, href TEXT NOT NULL, image_url TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS education (id SMALLINT PRIMARY KEY, period TEXT NOT NULL, institution TEXT NOT NULL, degree TEXT NOT NULL, location TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS experience (id SMALLINT PRIMARY KEY, position SMALLINT NOT NULL UNIQUE, period TEXT NOT NULL, role TEXT NOT NULL, company TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS experience_item (id SMALLINT PRIMARY KEY, experience_id SMALLINT NOT NULL REFERENCES experience(id) ON DELETE CASCADE, position SMALLINT NOT NULL, body TEXT NOT NULL, UNIQUE(experience_id, position));
CREATE TABLE IF NOT EXISTS project (id SMALLINT PRIMARY KEY, position SMALLINT NOT NULL UNIQUE, project_type TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL, url TEXT NOT NULL, thumbnail_url TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS project_tag (id SMALLINT PRIMARY KEY, project_id SMALLINT NOT NULL REFERENCES project(id) ON DELETE CASCADE, position SMALLINT NOT NULL, value TEXT NOT NULL, UNIQUE(project_id, position));
CREATE TABLE IF NOT EXISTS skill_group (id SMALLINT PRIMARY KEY, position SMALLINT NOT NULL UNIQUE, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS skill (id SMALLINT PRIMARY KEY, group_id SMALLINT NOT NULL REFERENCES skill_group(id) ON DELETE CASCADE, position SMALLINT NOT NULL, name TEXT NOT NULL, UNIQUE(group_id, position));

INSERT INTO profile VALUES (1, 'Alvan Marvianto', 'Backend Engineer · Distributed Systems · DevOps', 'Software Engineering undergraduate with hands-on experience in backend development, distributed systems, and cloud-native technologies. Building reliable APIs, event-driven integrations, and infrastructure that ships.', 'Open to backend, platform, and infrastructure opportunities', 'Bandung, Indonesia', 'ALVAN//SYS', 'SYSTEM PROFILE / 2026', 'BUILDING SYSTEMS THAT MOVE DATA, NOT JUST SCREENS.', 'EXECUTION LOG', 'PROJECTS', 'TOOLCHAIN', 'EDUCATION', 'LET''S BUILD THE NEXT SYSTEM.', 'INITIATE CONTACT', 'SYSTEM STATUS', 'ONLINE') ON CONFLICT DO NOTHING;
INSERT INTO navigation VALUES (1,'ABOUT','#about'),(2,'EXPERIENCE','#experience'),(3,'PROJECTS','#projects'),(4,'STACK','#stack') ON CONFLICT DO NOTHING;
INSERT INTO social_link VALUES (1,'EMAIL','alvanmarvianto@gmail.com','mailto:alvanmarvianto@gmail.com','https://minio.alvan.my.id/portfolio-assets/icons/email.svg'),(2,'LINKEDIN','linkedin.com/in/alvanm','https://linkedin.com/in/alvanm/','https://minio.alvan.my.id/portfolio-assets/icons/linkedin.svg'),(3,'GITHUB','github.com/alvanmarvianto','https://github.com/alvanmarvianto/','https://minio.alvan.my.id/portfolio-assets/icons/github.svg') ON CONFLICT DO NOTHING;
INSERT INTO education VALUES (1,'AUG 2022 — AUG 2026','Telkom University','Bachelor’s Degree in Software Engineering','Bandung, Indonesia') ON CONFLICT DO NOTHING;
INSERT INTO experience VALUES (1,1,'SEP 2025 — MAR 2026','Backend Developer','Direktorat Pusat Teknologi Informasi · Telkom University'),(2,2,'JUL 2025 — AUG 2025','Software Engineer Intern','Bank Indonesia'),(3,3,'SEP 2024 — JUN 2026','Practicum Assistant','Informatics Lab'),(4,4,'JUN 2024 — JUN 2026','Research Assistant','Adaptive Network Laboratory'),(5,5,'MAR 2025 — MAY 2025','Mentor · NetDev','Adaptive Network Laboratory') ON CONFLICT DO NOTHING;
INSERT INTO experience_item VALUES (1,1,1,'Designed NestJS REST APIs that integrate data across university information systems.'),(2,1,2,'Refactored database queries with parameterized queries and input validation to mitigate SQL injection risks.'),(3,1,3,'Designed and evaluated event-driven data synchronization using Debezium CDC and message brokers.'),(4,2,1,'Built an enterprise integration management system for applications, contracts, payments, and technology stacks.'),(5,2,2,'Developed interactive integration visualizations and admin dashboards.'),(6,2,3,'Built RESTful services and Redis caching to reduce redundant database queries.'),(7,3,1,'Delivered weekly programming labs to 100+ students per semester across data structures, OOP, OS, web, mobile, testing, and software construction.'),(8,3,2,'Provided personalized debugging support that connects theory with production practice.'),(9,4,1,'Conducted 5G core network monitoring research, benchmarking Istio and Cilium.'),(10,4,2,'Maintained the lab official website and its technical presence.'),(11,5,1,'Guided mentees through NDN, SDN, Docker, and Django.'),(12,5,2,'Led weekly technical discussions and provided final-project feedback.') ON CONFLICT DO NOTHING;
INSERT INTO project VALUES (1,1,'UNDERGRADUATE THESIS','Event-Driven Data Synchronization','One-way CDC synchronization architecture between microservice and legacy systems, evaluating Debezium with Kafka, RabbitMQ, and Redpanda.','https://github.com/alvanmarvianto','https://minio.alvan.my.id/portfolio-assets/projects/event-sync.svg'),(2,2,'RESEARCH','5G Core Network Monitoring','Service-mesh monitoring research for 5G Core environments, benchmarking Istio and Cilium with throughput and latency measurements.','https://github.com/alvanmarvianto','https://minio.alvan.my.id/portfolio-assets/projects/5g-monitoring.svg'),(3,3,'APPLICATION','NewCity','Multi-platform civic reporting system with citizen and government mobile apps plus an administrative web dashboard.','https://github.com/alvanmarvianto','https://minio.alvan.my.id/portfolio-assets/projects/newcity.svg') ON CONFLICT DO NOTHING;
INSERT INTO project_tag VALUES (1,1,1,'DEBEZIUM'),(2,1,2,'KAFKA'),(3,1,3,'RABBITMQ'),(4,1,4,'REDPANDA'),(5,2,1,'ISTIO'),(6,2,2,'CILIUM'),(7,2,3,'KUBERNETES'),(8,3,1,'LARAVEL'),(9,3,2,'FLUTTER'),(10,3,3,'VUE.JS') ON CONFLICT DO NOTHING;
INSERT INTO skill_group VALUES (1,1,'PROGRAMMING'),(2,2,'BACKEND'),(3,3,'DATA'),(4,4,'INFRA'),(5,5,'CLIENT') ON CONFLICT DO NOTHING;
INSERT INTO skill VALUES (1,1,1,'Go'),(2,1,2,'C++'),(3,1,3,'C#'),(4,1,4,'Java'),(5,1,5,'Python'),(6,2,1,'NestJS'),(7,2,2,'Spring Boot'),(8,2,3,'Laravel'),(9,3,1,'PostgreSQL'),(10,3,2,'MongoDB'),(11,3,3,'Oracle'),(12,3,4,'Kafka'),(13,3,5,'RabbitMQ'),(14,3,6,'Redpanda'),(15,3,7,'Debezium'),(16,4,1,'Docker'),(17,4,2,'Kubernetes'),(18,4,3,'Linux'),(19,5,1,'Vue.js'),(20,5,2,'Flutter') ON CONFLICT DO NOTHING;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'portfolio_rdbms') THEN
    GRANT SELECT, UPDATE ON ALL TABLES IN SCHEMA public TO portfolio_rdbms;
  END IF;
END $$;
